obstacles: null
stochastic_resets: False
render: False
apply_perturb: False
avg_time_per_perturb: 5.0 # seconds
action_repeat: 4 # TODO change back to 6
vis: False
max_torque: 44.4 # from URDF
kp: 1.0
kd: 1.0
fixed: False
fixed_position: [0,0,1.0] #TODO remove
fixed_orientation: [0,0,0] #TODO remove
observation_parts: #TODO enumerate all possible types that I can even put here. Also add terrain heightmaps
  - joint_torques
  - joint_positions
  - joint_velocities
  - base_angular_velocity
  - base_roll
  - base_pitch
  # - base_linear_acceleration #TODO

# possible values ['joint_positions', 'joint_velocities', 'joint_torques']
# eventually add pmtg and footstep_param stuff
# null means to use the widest bounds allowed ie no additional restriction imposed
action_space:
  Iscen_PMTG: # This pmtg is the original one from "Policies Modulating Trajectory Generators"
    gait: trot # allowed: trot, walk
    amplitude_bounds:
      lb: 0.0
      ub: 0.3
    walking_height_bounds: # this is just negative step_bottom
      lb: 0.25
      ub: 0.6
    frequency_bounds:
      lb: 0.75
      ub: 2.00
    residual_bounds:
      lb: -0.1
      ub: 0.1
    step_height: 0.15
    x_offset: 0.02109375
    lateral_offset: 0.075

reward_parts: #TODO
  # reward_type: coefficient
  # note: the reward bounds are on the measured value of the thing, not on the reward term
  forward_velocity: [1.0, -1.5, 1.5] #coeffient, lower bound, upper bound
  joint_torques_sq: [-0.000005]

termination_conditions: #obstacles and foostep_param will automatically include their own termination conditions (ie traveling outside of generated terrain)
  height_bounds: [0.23, 0.8] # [lb, ub] this will automatically be turned off if obstacles are included
  orientation_bounds: [0.5, 0.25, 0.25] # multiples of pi
  timeout: [60] # seconds