wandb_project: ARS_Lunar_Lander
algo: ars
lr: 0.0015
n_dirs: 10
top_dirs: 1
delta_std: 0.025
top_dirs_frac: null
eval_int: 10
eval_runs: 1
env_name: LunarLanderContinuous-v2
n_samples: 10_000_000
save_int: 1000000
